version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: treesindia-backend-prod
    ports:
      - "7080:7080"
    volumes:
      - ./FCM-FIREBASE:/app/FCM-FIREBASE:ro
    networks:
      - treesindia-network
    env_file:
      - .env.production
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:${PORT}/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Production-specific settings
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

networks:
  treesindia-network:
    driver: bridge
    enable_ipv6: true
