version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: treesindia-backend
    ports:
      - "8080:8080"
    volumes:
      - ./FCM-FIREBASE:/app/FCM-FIREBASE:ro
    networks:
      - treesindia-network
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  treesindia-network:
    driver: bridge
    enable_ipv6: true
